DROP INDEX IF EXISTS idx_book_author;
DROP INDEX IF EXISTS idx_book_year;
DROP INDEX IF EXISTS idx_book_genre;

DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS "uuid-ossp";